### ISSUE TITLE
New `bpmn-moddle` version is incompatible with the node v16

### ISSUE THREAD

**Issue by corocoto** [bpmn-io/bpmn-moddle#113]
### Describe the Bug

I tried to upgrade the `bpmn-moddle` package to it's latest version by using Node v16. After trying it, I got an error. 

The main reason why it's happen is that `bpmn-moddle` using the latest `moddle-xml` package. And the latest version of `moddle-xml` [only compatible with node' versions >= 18](https://github.com/bpmn-io/moddle-xml/blob/main/package.json#L46).

### Steps to Reproduce

1. Install Node.js v16
2. Try to install `bpmn-moddle` 
3. Get an error linked on the node's version:
```bash
error moddle-xml@11.0.0: The engine "node" is incompatible with this module. Expected version ">= 18". Got "16.14.2"
error Found incompatible module.
```

### Expected Behavior
It can have two resulted ways:
1. `bpmn-moddle` will install correctly with node v16
2. Upgrade `bpmn-moddle`'s `engines` field. By setting `">= 18"` (instead of [current configuration with `">= 16"`](https://github.com/bpmn-io/bpmn-moddle/blob/main/package.json#L30C14-L30C19)). To show that the latest `bpmn-moddle` package version is only compatible with node' versions >= 18

### Environment

- Host (Browser/Node version), if applicable: Node v16.14.2
- OS: macOS 14.2.1
- Library version: latest

**Comment by barmac** [comment]
Thanks for sharing. Note that Node 16 is out of support, and the most recent supported version is 18: https://nodejs.org/en/about/previous-releases

We will update the `engines` field as you suggested.
