### ISSUE TITLE
Add explicit build for meta-model

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/bpmn-moddle#23]
Currently, the json metamodel is created from cmof when running the test suite. This has several drawbacks:
- Tests should not persistently change resources outside their test environment
- When changing the json, the tests fail initially, as the updated json is only respected in subsequent test runs

To solve this, I propose the following changes:
- create a new grunt target (e.g. build), which performs the cmof to json conversion
- remove "tests" from testsuite, that do not test anything, but perform the build (i.e. the whole spec/adapter directory)
- optionally test the cmof to json conversion in a sandboxed test
- optionally add additional grunt target "auto-build" (perform build on change and run the tests)

**Comment by nikku** [comment]
We'd still appreciate a pull-request for this but won't work on this any times soon.

Closing this for now.
