### ISSUE TITLE
Process#property is serialized in the wrong place

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-moddle#24]
`<property>` tags should be serialized before flowNodes. This is something we do not take into account right now.

[Related forum post](https://forum.bpmn.io/t/property-definitions-not-in-the-right-order-when-exported-to-xml/396).

**Comment by wkit23** [comment]
Anyone is working on this? Any status?

**Comment by nikku** [comment]
We are not working on this one at the moment.

Fixing the underlying issue is a bit more complicated as it is caused by a miss-match between the BPMN 2.0 meta-model and the XSD schema (with regard to the order in which element properties are defined). 

We need to rewrite the inheritance hierarchy (probably starting at [`FlowElementsContainer`](https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/bpmn.json#L1644)).

A better and probably more robust way to approach this is to allow the redefinition of property order in sub-classes. This is something we would need to implement in [moddle](https://github.com/bpmn-io/moddle).

**Comment by wkit23** [comment]
I see. I was facing the same problem with sequence and temporary just perform a workaround by reordering it manually for what I need. Anything I can help?

**Comment by nikku** [comment]
You could provide a PR that fixes the issue :smiley:. But that really depends on how deep you'd like to dive into the project.
