### ISSUE TITLE
Import BPMN file in NodeJS

### ISSUE THREAD

**Issue by ramonck** [bpmn-io/bpmn-moddle#26]
Srs.,

I created a test BPMN file in order to test the import of the moddler, I get an error.

![image](https://cloud.githubusercontent.com/assets/5229948/9860394/4bd3b398-5b02-11e5-8752-4c1dde8a66e8.png)

Save the file above as BPMN extension (it's the diagram I created as example)

![diagram bpmn](https://cloud.githubusercontent.com/assets/5229948/9860343/e945586c-5b01-11e5-88b0-85db4a439e66.png)

The Code:

```
var BpmnModdle = require('bpmn-moddle');
var fs = require("fs");
var filename = "diagrama.bpmn";
var moddle = new BpmnModdle();
var xmlStr;
fs.readFile(filename, "utf8", function(err, data) {
        if (err) throw err;
        xmlStr = data;
        console.dir(xmlStr);
        console.log("diagrama read");
});

moddle.fromXML(xmlStr, function(err, definitions) {
  if (err) throw err;

  console.dir(definitions);

});
```

**Comment by nikku** [comment]
You need to correctly deal with the async nature of `fs#readFile` and `moddle#fromXML`, i.e.:

```javascript
fs.readFile(..., function(..., data) {
  moddle.fromXML(data, function(err, definitions) {
   console.log('YEP, definitions', definitions);
  });
});
```
