### ISSUE TITLE
Diagram Import error on parsing

### ISSUE THREAD

**Issue by ramonck** [bpmn-io/bpmn-moddle#27]
Parsing this diagram: 
http://jsfiddle.net/q45m9bv4/

Got this error: 
![image](https://cloud.githubusercontent.com/assets/5229948/9903509/50358924-5c4d-11e5-9475-50fb1297728b.png)

Created the diagram with demo.bpmn.io

Best Regards,

**Comment by nikku** [comment]
This is because you do not declare a `bpmn` namespace prefix in XML. In your diagram it is called `bpmn2`.
