### ISSUE TITLE
BPMNDiagram#name and BPMNDiagram#resolution not serialized correctly

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-moddle#31]
Serialization prepends the `di` namespace to the following XML (after roundtrip):

```
...
  <bpmndi:BPMNDiagram id="Diagram_1" name="New Diagram" resolution="96.0">
...
```

The solution is to not serialize the namespace for inherited attributes.

**Comment by falko** [comment]
This causes the following exception when deploying into Camunda BPM:
org.camunda.bpm.engine.ProcessEngineException: cvc-complex-type.3.2.2: Attribute 'di:name' is not allowed to appear in element 'bpmndi:BPMNDiagram'. | process.bpmn | line 15 | column 82

**Comment by falko** [comment]
137 BPMN models in camunda/camunda-consulting are affected by this

**Comment by meyerdan** [comment]
Are you sure?

**Comment by falko** [comment]
Okay, I accidentally counted my local target directories. But at 65 examples are still enough.

**Comment by meyerdan** [comment]
I am just messin with ya :C Thanks for providing this feedback!

**Comment by nikku** [comment]
This project does not seem to be ready for consulting, yet :cat:
