### ISSUE TITLE
Can proprieties inherit from 'type' while using 'name' for their xml tags

### ISSUE THREAD

**Issue by flehoux** [bpmn-io/bpmn-moddle#36]
Hi,

I was wondering if it was possible for a propriety to inherit it's definition from a type but to use it's own name as the tag when serializing to xml.

I could almost do it by modifying the `$descriptor.ns.localName` attribute of my newly created moddle objects but as I quickly realized, the descriptor is bound to the type and shared across it's instances. This was almost a viable solution :P

I've included three snippets below in case this was not clear

```javascript
{
    "name": "TypeDefinition",
    "properties": [
        {
            "name": "label",
            "type": "ProprietyDefinition"
        },
        {
            "name": "value",
            "type": "ProprietyDefinition"
        }
    ]
}
```

This is the result i'd be looking for

```xml
...
<abc:typeDefinition>
    <abc:label randomAttr="...">randomBody</abc:label>
    <abc:value randomAttr="...">randomBody</abc:value>
</abc:typeDefinition>
...
```

This is what I actually get right now

```xml
...
<abc:typeDefinition>
    <abc:proprietyDefinition randomAttr="...">randomBody</abc:proprietyDefinition>
    <abc:proprietyDefinition randomAttr="...">randomBody</abc:proprietyDefinition>
</abc:typeDefinition>
...
```

Thanks!

**Comment by nikku** [comment]
Yes. You need to provide a `xmn -> serialize: property` hint.

See [bpmn.json](https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/bpmn.json#L959).
