### ISSUE TITLE
Process#interfaceRef not correctly imported

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-moddle#37]
Trying it gives us:

> unparsable content <bpmn2:interfaceRef> detected
>          line: 200
>          column: 26
>          nested error: unknown type <bpmn:InterfaceRef>

**Comment by gimbel** [comment]
Any chance to get that into the recent milestone? Then we have that off our chest

**Comment by nikku** [comment]
Fix waiting to be reviewed.
