### ISSUE TITLE
default flow ("default") property not in JSON meta-model output

### ISSUE THREAD

**Issue by snoop244** [bpmn-io/bpmn-moddle#46]
My default flow shows in the XML but not in the JSON.  It appears to be in bpmn-moddle/resources/bpmn/json/bpmn.json file as a property of the various gateways but does not show in the JSON output when Moddle.

**Comment by nikku** [comment]
I don't understand the thing you are trying to report. Please be provide some examples that allow to reproduce the thing you experience.

**Comment by snoop244** [comment]
On line 48 of the attached BPMN file created in Camunda Modeler you will see an exclusive gateway with the property "default".  It shows the sequence flow that helps me default the default flow in my code.  

 <bpmn:exclusiveGateway id="ExclusiveGateway_0lhs7no" default="SequenceFlow_0r71us8">

I could be mistaken, but I assume the bpmn.json file in the resources folder of this repo acts like a schema.  Here is a link to the line in that file that suggests that an exclusive gateway can have a property called "default" of type "SequenceFlow"

https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/bpmn.json#L359

The output for the ExclusiveGateway from Moddle looks like this:

    {  
      "$type":"bpmn:ExclusiveGateway",
      "id":"ExclusiveGateway_0lhs7no"
    },

I expected it to look like this:

    {  
      "$type":"bpmn:ExclusiveGateway",
      "id":"ExclusiveGateway_0lhs7no",
      "default":"SequenceFlow_0r71us8""
    }


[testFlow.bpmn.zip](https://github.com/bpmn-io/bpmn-moddle/files/787819/testFlow.bpmn.zip)

**Comment by nikku** [comment]
Inspect the given JavaScript object via your favorite development tools and you will see that the property is there during modeling.

It is just not being exported once you `JSON.stringify(obj)`, as non-containment relations ae stored as non-enumerable properties in the schema.

**Comment by snoop244** [comment]
Thanks. I never thought off that!
