### ISSUE TITLE
Tests reset "enumerations"-fields to "emumerations"

### ISSUE THREAD

**Issue by felixlinker** [bpmn-io/bpmn-moddle#48]
I don't know why this is happening but it might be the reason for why my PR #47 was necessary in the first place.

Whenever I run `grunt` or `grunt test` all occasions of `enumerations` are set to `emumerations`.

Steps to reproduce:
1. `git clone https://github.com/bpmn-io/bpmn-moddle.git`
2. `npm install`
3. `grunt test`
4. `git diff` => See and wonder

**Comment by nikku** [comment]
Did you try to search the existing code bases for it to see if you can fix this?

**Comment by felixlinker** [comment]
I tried to search this repository on master branch for the word `emumerations` but wasn't able to find something.

**Comment by nikku** [comment]
What about [this](https://github.com/bpmn-io/cmof-parser/search?utf8=%E2%9C%93&q=emumerations&type=). 

So the previous fix was actually just a temporary one :cake: :smiley:.

**Comment by felixlinker** [comment]
https://github.com/bpmn-io/cmof-parser/pull/1

**Comment by nikku** [comment]
Closed via bpmn-io/cmof-parser#1.
