### ISSUE TITLE
XSD Extensions to JSON

### ISSUE THREAD

**Issue by EduFrazao** [bpmn-io/bpmn-moddle#52]
Hi. I want to write a Activiti BPMN moddle extension, like the Camunda one.
Do you use some tool to parse the XSD and write the JSON equivalent?
Can anyone any documentation about it?

PS: The camunda extension that is used in test classes in this project uses the Activiti XSD Namespace many times. Camunda have more extensions than Activiti or they are compatible?

Thanks!

**Comment by nikku** [comment]
> Do you use some tool to parse the XSD and write the JSON equivalent?

You can use the XSD as a reference, however it hides important information such as relationships. The [Camunda extension](https://github.com/camunda/camunda-bpmn-moddle) is hand made. The repository and the contained test cases should give you a good indication what to build and how to test it.

> The camunda extension that is used in test classes in this project uses the Activiti XSD Namespace many times. Camunda have more extensions than Activiti or they are compatible?

Camunda [forked Activiti](http://www.bpm-guide.de/) years ago. There is some overlapping in attributes but nowadays non of these projects claims to be compatible with the other.
