### ISSUE TITLE
how can i generate a .bpmn with events

### ISSUE THREAD

**Issue by xgodon** [bpmn-io/bpmn-moddle#54]
I'm a bit inexperimented with bpmn and i'm trying to generate a bpmn file that i can open with camunda.
i understand that i need to add something like : 

<bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="MyProcess_1">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="173" y="102" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>

but i can't manage to make it work and i could use some exemples and how to create different shapes...

I tried this but the var result = "undefined"

function addEvent(){

  moddle.fromXML(xmlStr, function(err, definitions) {

      // add a root element
      var bpmnTask = moddle.create('bpmn:Task', { id: "tache" });
      definitions.get('rootElements').push(bpmnTask);

      var bpmnShape = moddle.create('bpmndi:BPMNShape', { id: "shape_tache" , bpmnElement: "tache" });
      definitions.get('rootElements').push(bpmnShape);

      moddle.toXML(definitions, function(err, xmlStrUpdated) {

        result = xmlStrUpdated;
      });
  });
}

**Comment by nikku** [comment]
I'd suggest you to have a look at our [test coverage](https://github.com/bpmn-io/bpmn-moddle/tree/master/test/spec/xml) to better understand how the library works.

If you're using [bpmn-js](https://github.com/bpmn-io/bpmn-js) anyway [bpmn-js-cli](https://github.com/bpmn-io/bpmn-js-cli) may be a simpler solution than to generate everything by hand.
