### ISSUE TITLE
Should the import statements not specify the file with a ".js" extension?

### ISSUE THREAD

**Issue by nkolban** [bpmn-io/bpmn-moddle#57]
I was trying to consume this project in a Chrome browser and ended up getting 404 not found errors.  I'm not very skilled in ES6 modules but after some reading, it appears that Chrome requires the path to the module to include the ".js" suffix.  Is there a reason that the suffix hasn't been added to the paths in this package?  Would it be a good idea to add them?

**Comment by nikku** [comment]
Please consider bundling the library.

If you use [bpmn-js](https://github.com/bpmn-io/bpmn-js) consider our [pre-packaged distribution](https://github.com/bpmn-io/bpmn-js-examples/tree/master/pre-packaged) which works in the browser out of the box.

Consuming it as is in Chrome is not possible as far as I understand.

Quoting from the library readme:

> Use esm to consume it or a ES module aware transpiler such as Webpack, Rollup or Browserify + babelify to bundle it for the browser.
