### ISSUE TITLE
$type field

### ISSUE THREAD

**Issue by kozhuhds** [bpmn-io/bpmn-moddle#58]
hey! can you help me with one thing: is it possible to set $type field object descriptor to writable, just faced with the troubles when I need to modify type of element

**Comment by nikku** [comment]
What is your use case? Why would you like to change the `$type` of an element?

**Comment by kozhuhds** [comment]
I use bpmn-moddle as data structure for my app and I need to change type of element for example: changing bpmn:InclusiveGateway to bpmn:ComplexGateway.

**Comment by nikku** [comment]
By definition, elements with different types have different properties. Changing the `$type` won't get you anywhere. The right way to change elements is to create a new element and copy the allowed properties from the old to the new one.
