### ISSUE TITLE
Choreography activity participantRef(s)

### ISSUE THREAD

**Issue by jan-ladleif** [bpmn-io/bpmn-moddle#59]
Hi everyone,

we're currently working on a BPMN 2.0 choreography diagram modeler ([chor-js](https://github.com/jan-ladleif/chor-js), [chor-js-demo](https://github.com/jan-ladleif/chor-js-demo)) based on bpmn-js and bpmn-moddle. We've noticed some inconsistencies regarding the name of the [`participantRefs`](https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/bpmn.json#L2064) association on Choreography Activity (and Conversation Node).

Apparently, depending on where you look, the trailing `s` is sometimes missing:

| `participantRef`       | `participantRefs` (with s)                         |
|----------------------|------------------------------------------|
| [BPMN 2.0 XSD](https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/xsd/Semantic.xsd#L238)         | [BPMN 2.0 CMOF](https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/cmof/BPMN20.cmof#L972)                            |
| Signavio             | BPMN 2.0 standard document (in the text) |
| [Eclipse BPMN2 Modeler](https://www.eclipse.org/bpmn2-modeler/) | **bpmn-moddle**       |

Our [current plan](https://github.com/jan-ladleif/chor-js/issues/45) is to be able to import both versions, and export the `participantRef` version for compatibility with Signavio and the Eclipse BPMN2 Modeler.

**Suggestion:** We are not aware of any tool using the `participantRefs` version found in the CMOF, so the workarounds could be scraped if the association was renamed to `participantRef` in bpmn-moddle as well.

**Comment by nikku** [comment]
Thanks for reporting :heart:. 

This library is meant to be a general purpose library for validating and consuming and producing BPMN 2.0 XML documents. If the schema contains a bug, i.e. is unable to consume or produce valid BPMN 2.0 XML (or produce it) we must fix this issue.

The namings of variables are not set in stone, in fact they are solely the result of generating the `bpmn.json` meta model from the BPMN 2.0 CMOF. We already address numerous issues during the automated conversion process, inspect them [here](https://github.com/bpmn-io/bpmn-moddle/blob/master/test/spec/adapter/cmof/generate-simple.js#L14).

Could you share valid diagrams that are not handled correctly as of now? That allows us to do further investigation.

Please consider creating a pull request that contains the relevant test cases for round-tripping a valid BPMN 2.0 diagram using our library (cf. [roundtrip tests](https://github.com/bpmn-io/bpmn-moddle/blob/master/test/spec/xml/roundtrip.js)). This usually speeds up our report-to-fix cycle times :wink:. Starting based of an existing PR I am happy to improve the test coverage and implement the actual fix in our [conversion process]([here](https://github.com/bpmn-io/bpmn-moddle/blob/master/test/spec/adapter/cmof/generate-simple.js#L14)).

**Comment by nikku** [comment]
> We're currently working on a BPMN 2.0 choreography diagram modeler (chor-js, chor-js-demo) based on bpmn-js and bpmn-moddle. 

I am personally super exited about this one, by the way!

**Comment by jan-ladleif** [comment]
Thank you for the quick reply! I've prepared a branch locally but for some reason cannot seem to push it (permission denied). Are there any restrictions on the repo?

**Comment by nikku** [comment]
Closed via 0f8469983378c85c1c98281819c4c87d50190ce5.
