### ISSUE TITLE
Strict MIME type checking is enforced for module scripts

### ISSUE THREAD

**Issue by kvsrohit** [bpmn-io/bpmn-moddle#61]
I am using bpmn-js as pure ES6 modules in browser without any transpilation. (wrapping BpmnModeler into a Polymer-3 component)

Following import
> `import {BpmnModdle} from 'bpmn-moddle';`

triggers `bpmn-moddle/lib/simple.js` load and json import statements in this file 

> `import BpmnPackage from '../resources/bpmn/json/bpmn.json';`

cause the error as only JS modules (application/javascript) can be imported and not other mime types like application/json.

> ... Strict MIME type checking is enforced for module scripts ...

Can bpmn-js / bpmn-moddle be used as pure ES6 modules without any transpilation?

**Comment by nikku** [comment]
> Can bpmn-js / bpmn-moddle be used as pure ES6 modules without any transpilation?

Not our primary target. We are open to input how that can be improved though.

**Comment by nikku** [comment]
Flagged this as `pr-welcome`. If you are interested in improving the pure ES 6 compatibility, help us out.
