### ISSUE TITLE
Unexpected token export in Node 10.15 CLI app

### ISSUE THREAD

**Issue by GeekMustHave** [bpmn-io/bpmn-moddle#62]
The older version of my NODE CLI app was working with Node 8.0 and the older version of your library.

I recently upgraded to Node 10.15 and did a new install of BPMN-Moddle, it shows up as  "bpmn-moddle": "^5.1.6", in `package.json`.

I have Babel-Node installed and when I run the babel-node index.js I get the following error.

C:\myDev\CAMUNDA to ASCIIDoctor\node_modules\bpmn-moddle\index.js:1
(function (exports, require, module, __filename, __dirname) { export {
                                                              ^^^^^^
SyntaxError: Unexpected token export.

I have other libraries in my Node CLI app like "camunda-bpmn-moddle": "^3.2.0", which do not appear to have any issue.

Any suggestions would be appreciated.

**Comment by nikku** [comment]
Could you share your setup? This would allow us to reproduce your issue.

**Comment by captainsano** [comment]
@GeekMustHave I ran into the same issue. Turns out that node cannot handle import/export yet. So, you can use `esm` to import `bpmn-moddle`,

```js
const BpmnModdle = require('esm')(module)('bpmn-moddle').default;

const moddle = new BpmnModdle();
```

**Comment by nikku** [comment]
That is correct and clearly documented in the project README, too.
