### ISSUE TITLE
How to get bpmn.json?

### ISSUE THREAD

**Issue by keven11111112** [bpmn-io/bpmn-moddle#69]
How to convert bpmn.json from bpmn.cmof?

**Comment by pinussilvestrus** [comment]
First: Please use [our forum](https://forum.bpmn.io/) to ask questions. GitHub issues are more intended for bug reports and feature requests.

Why do you need to convert the `.cmof` to the `.json` file? [`bpmn.json`](https://github.com/bpmn-io/bpmn-moddle/blob/master/resources/bpmn/json/bpmn.json) is already available.

You can use the [`cmof-parser`](https://github.com/bpmn-io/cmof-parser) to parse the `cmof` file.

**Comment by philippfromme** [comment]
We're in the process of [refactoring the generation of the JSON files from the CMOF files](https://github.com/bpmn-io/bpmn-moddle/tree/next). What is your use case?

**Comment by keven11111112** [comment]
> We're in the process of [refactoring the generation of the JSON files from the CMOF files](https://github.com/bpmn-io/bpmn-moddle/tree/next). What is your use case?

uml, sysml. thanks.

**Comment by philippfromme** [comment]
> uml, sysml. thanks.

Please explain. Thanks.

**Comment by keven11111112** [comment]
> > uml, sysml. thanks.
> 
> Please explain. Thanks.

I have uml.cmof and uml.ecore, how to convert to moddle json format?

**Comment by nikku** [comment]
We do not discuss anything here.

Refer to our forum, clearly describe where you're coming from where you'd like to go. Use sentences with more than two words. What do you like to achive and why and how can we help?

I suggest that we close this issue and lock the conversation.

**Comment by keven11111112** [comment]
> We do not discuss anything here.
> 
> Refer to our forum, clearly describe where you're coming from where you'd like to go. Use sentences with more than two words. What do you like to achive and why and how can we help?
> 
> I suggest that we close this issue and lock the conversation.

ok,thanks.
