### ISSUE TITLE
Include Typescript definitons in package

### ISSUE THREAD

**Issue by ceisele-r** [bpmn-io/bpmn-moddle#77]
__Is your feature request related to a problem? Please describe__

Since the types from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bpmn-moddle are outdated/out of sync with this package (`fromXML` and `toXML` do not return Promises), would it be possible to include up to date typescript types directly in this package?

__Describe the solution you'd like__

We would prefer to have typescript definitions directly included in this package since they will then reflect the actual code and simplifies usage of the package.

__Describe alternatives you've considered__

An alternative would be to somehow try to keep the types from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bpmn-moddle in sync with bpmn-moddle.

__Additional context__

N/A

**Comment by nikku** [comment]
I guess it makes sense to contribute to the definitely typed repository.

The API update is brand new and people simply did not have time to pull in the update, yet.

**Comment by steinroe** [comment]
any update here?

**Comment by nikku** [comment]
Which update do you expect, given [my previous comment](https://github.com/bpmn-io/bpmn-moddle/issues/77#issuecomment-614002313)?
