### ISSUE TITLE
Outgoing & incoming Support

### ISSUE THREAD

**Issue by thesolyd** [bpmn-io/bpmn-moddle#79]
There is no way to get outgoing and incoming node information in moddle. For example, in the test task - Choreography(below), there is no way to get the SequenceFlow_2 & SequenceFlow_1 for ChoreographyTask_1. How can we achieve the same?
`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" xmlns:signavio="http://www.signavio.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exporter="Signavio Process Editor, http://www.signavio.com" exporterVersion="8.4.1" expressionLanguage="http://www.w3.org/1999/XPath" id="sid-73c85f47-caf7-49f4-81c2-ccd9c46beedb" targetNamespace="http://www.signavio.com/bpmn20" typeLanguage="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL http://www.omg.org/spec/BPMN/2.0/20100501/BPMN20.xsd">
  <message id="someMessage" />
  <choreography id="Choreography_1" name="Default Choreography">
    <participant id="Participant_1" name="Initiating Participant"/>
    <participant id="Participant_2" name="Non-initiating Participant"/>
    <messageFlow id="MessageFlow" messageRef="someMessage" name="Message Flow" sourceRef="Participant_1" targetRef="Participant_2"/>
    <choreographyTask id="ChoreographyTask_1" name="Choreography Task" initiatingParticipantRef="Participant_1">
      <incoming>SequenceFlow_2</incoming>
      <outgoing>SequenceFlow_1</outgoing>
      <participantRef>Participant_1</participantRef>
      <participantRef>Participant_2</participantRef>
      <messageFlowRef>MessageFlow</messageFlowRef>
    </choreographyTask>
    <endEvent id="EndEvent_1" name="End Event 1">
      <incoming>SequenceFlow_1</incoming>
    </endEvent>
    <sequenceFlow id="SequenceFlow_1" sourceRef="ChoreographyTask_1" targetRef="EndEvent_1"/>
    <startEvent id="StartEvent_1" name="Start Event 1">
      <outgoing>SequenceFlow_2</outgoing>
    </startEvent>
    <sequenceFlow id="SequenceFlow_2" sourceRef="StartEvent_1" targetRef="ChoreographyTask_1"/>
  </choreography>
</definitions>`

Expected Solution:

> 
> const BpmnModdle = require('bpmn-moddle');
> const moddle = new BpmnModdle()
> const { rootElement: definitions } = await moddle.fromXML(xmlStr)
> //For a task node, get outgoing by: res['bpmn:StartEvent']['outgoing']
>

**Comment by thesolyd** [comment]
I tried adding FlowElementsContainer in BPMN20.cmof. But still this test cannot pass.
```

<ownedMember xmi:type="cmof:Class" xmi:id="StartEvent" name="StartEvent" superClass="FlowElementsContainer CatchEvent">
      <ownedAttribute xmi:type="cmof:Property" xmi:id="StartEvent-isInterrupting" name="isInterrupting" default="true">
        <type xmi:type="cmof:PrimitiveType" href="http://schema.omg.org/spec/MOF/2.0/cmof.xml#Boolean"/>
      </ownedAttribute>
    </ownedMember>
```

> 
> var expectedOutgoing = {
>         $type: 'bpmn:outgoing',
>       };
> expect(rootElement.outgoing).to.jsonEqual([expectedOutgoing]);

**Comment by thesolyd** [comment]
I suggest to break FlowNode into OutflowNode & InflowNode
`Current
<ownedMember xmi:type="cmof:Class" xmi:id="FlowNode" name="FlowNode" isAbstract="true" superClass="OutflowNode FlowElement">
      <ownedAttribute xmi:type="cmof:Property" xmi:id="FlowNode-outgoing" name="outgoing" type="SequenceFlow" isOrdered="true" upper="*" lower="0" association="A_sourceRef_outgoing_flow"/>
      <ownedAttribute xmi:type="cmof:Property" xmi:id="FlowNode-incoming" name="incoming" type="SequenceFlow" upper="*" lower="0" association="A_targetRef_incoming_flow"/>
      <ownedAttribute xmi:type="cmof:Property" xmi:id="FlowNode-lanes" name="lanes" type="Lane" upper="*" lower="0" isDerived="true" association="A_flowNodeRefs_lanes"/>
    </ownedMember>
`

`Suggestion
<ownedMember xmi:type="cmof:Class" xmi:id="FlowNode" name="FlowNode" isAbstract="true" superClass="OutflowNode InflowNode FlowElement">
      <ownedAttribute xmi:type="cmof:Property" xmi:id="FlowNode-lanes" name="lanes" type="Lane" upper="*" lower="0" isDerived="true" association="A_flowNodeRefs_lanes"/>
    </ownedMember>
    <ownedMember xmi:type="cmof:Class" xmi:id="OutflowNode" name="OutflowNode" isAbstract="true" superClass="FlowElement">
      <ownedAttribute xmi:type="cmof:Property" xmi:id="OutflowNode-outgoing" name="outgoing" type="SequenceFlow" isOrdered="true" upper="*" lower="0" association="A_sourceRef_outgoing_flow"/>
    </ownedMember>
    <ownedMember xmi:type="cmof:Class" xmi:id="InflowNode" name="InflowNode" isAbstract="true" superClass="FlowElement">
      <ownedAttribute xmi:type="cmof:Property" xmi:id="InflowNode-incoming" name="incoming" type="SequenceFlow" isOrdered="true" upper="*" lower="0" association="A_targetRef_incoming_flow"/>
    </ownedMember>
`

This way, Start Nodes and End Nodes, having only Outgoing and Incoming node information can be parsed.
What do you think folks?
Please suggest

**Comment by nikku** [comment]
Why did you close this one? Were you able to address your issue? What was the resolution then?
